name: szoplugin
main: wentuziak.szoplugin.SzoPlugin
version: 0.0.1
api-version: 1.21
commands:
  szopCow:
    description: "Summon an exploding cow uwu"
    usage: "/szopCow [baby]"
    aliases: [ szoplugin ]
    permissions: szoplugin.command.szopCow
    permission-message: "You do not have the permissions to summon an exploding cow"
  swapRace:
    description: "Change players race"
    usage: "/swaprace [race] [player]"
    aliases: [ szoplugin ]
    permissions: szoplugin.command.swapRace
    permission-message: "You do not have the permissions to swap races"
  removeRace:
    description: "Remove players race"
    usage: "/removerace [race] [player]"
    aliases: [ szoplugin ]
    permissions: szoplugin.command.removeRace
    permission-message: "You do not have the permissions to remove races"